spring.application.name=customerservice

spring.datasource.url=jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.data.mongodb.uri=mongodb://localhost:27017/customer_audit_db

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

app.policies=classpath:policies/policy.yml
app.certKeyPart=QDZaVxJDG/8yKWoMAorBTak0Y24Ee8JZjN+MdeilYnNRy9C0LmSt043QBiFRKetwDHpUeEJerQW3ID+SnpUtZDlSjhdNgTzZOo4W2AeIqGaCVuF5rJMZ9WKwepKQthpFaCTJA5faGaWGOTcrhucRnuUANcs3ALYPlr6c3cjgGMFHQKBgA9RbVfNXTpt+SE9E7KMOTffwAGFlTWxf86GbkUtFXlayEyS32+PP8W2dRrR+90zYlu4iY4TLFFgwiS9OzJErvqtBOaFBimKvBlh91WgjoJuUrtVGwQZScRbBvKta+1p1998eTAPnmD/x7eRdDjRj88bs7Sk4s/0nygvPgkPYawvAoGBAMHqHavx8fjPpiHLJ2aTsdd0KSlipYgGpisKncCgDFcSBO9daAeag6L4Ambrg3uQD3SB2WwxC2vQpSUqnM3tXB2HA5rv0Z6eBeLabXKzhNv1OLLHv4QyoN6wcx5lXMztw1k6Ma+bWNTLw2WpzWqn2xV5YnLakZb6lv8H+d2qZ6dpAoGAYakBCoVJvJOFZqo9qSkdL1nLwkQJMzrLSkJlLDAXev5KK/7Tk8KRxNe/MUzSSwGGbU64djNZGPCtnNxJTR+YaZYp0CzOD65+eU/NEZvi4jIyfgWl1GIXPYuqN8GJ2A3jCL//lGnvTWZnKl3EdFVl3IRbgT2SRuhqKVhXw6WLqCU=
app.credsFilePath=src/main/resources/policies/global.secret.enc.properties
app.certStorePath=src/main/resources
bpi.backendadapter.enabled=true

bpi.api.inquire-branch.basePath=http://localhost:3000/inquire-branch
bpi.api.inquire-branch.connect-timeout=10000
bpi.api.inquire-branch.socket-timeout=10000


bpi.soap.wsrvalng.endpoint-url=http://localhost:3000/soap/validateAcctNumber
bpi.soap.wsrvalng.connect-timeout=10000
bpi.soap.wsrvalng.read-timeout=10000

bpi.soap.api.configure.enabled=true

soap.inquire-customer.endpoint-url=http://localhost:3000/soap/inquire-customer